name: Build and deploy Node.js app to Azure Web App - FlingDisc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests (Optional)
        run: |
          set CI=false
          npm test || echo "Skipping tests, continuing deployment"

      - name: Build React App
        run: npm run build

      - name: Upload build folder for deployment
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for JWT authentication
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build  # Ensure correct extraction

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ED43B86CA96E4B3F9997531C6ACDA7E1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BC93B50ED72A46DABDF99BBC7E0371CB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F7D5C88069654C4AABDF4962FDC7DDB8 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'FlingDisc'
          slot-name: 'Production'
          package: build  # Deploy build folder only
